language: node_js
node_js: "10"
install:
  - npm install
jobs:
  include:
    - stage: unit tests with coverage
      script: yarn coverage
    - stage: run lint and build
      script: yarn run lint && yarn build
    - stage: npm release
      if: branch IN (npm-release) AND NOT type IN (pull_request) # this is that travis dosnt create a "deploy" job in an commit other than in "npm-release"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: "kpfromer2@gmail.com"
        api_key: $NPM_API_KEY
      on: npm-release
    - stage: deploy documentation
      if: branch IN (master) AND NOT type IN (pull_request)
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn deploy
      on: master
